// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUbyYXWmxutsuexilGguNRkuOw3HnTt94',
    appId: '1:745750974335:web:4a87b0b98507112aa1144a',
    messagingSenderId: '745750974335',
    projectId: 'proyecto-eventos-1da9f',
    authDomain: 'proyecto-eventos-1da9f.firebaseapp.com',
    storageBucket: 'proyecto-eventos-1da9f.firebasestorage.app',
    measurementId: 'G-9R33T7B1ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcoONB8Qx8NUY_J72R0CCWg_1t0Rm8DZA',
    appId: '1:745750974335:android:428ae18553bc613aa1144a',
    messagingSenderId: '745750974335',
    projectId: 'proyecto-eventos-1da9f',
    storageBucket: 'proyecto-eventos-1da9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxpq2NqfG8kJwLNkiv568bmPsqG36_7Eg',
    appId: '1:745750974335:ios:33ad3adc507e9cc9a1144a',
    messagingSenderId: '745750974335',
    projectId: 'proyecto-eventos-1da9f',
    storageBucket: 'proyecto-eventos-1da9f.firebasestorage.app',
    iosBundleId: 'com.example.proyectoEventos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxpq2NqfG8kJwLNkiv568bmPsqG36_7Eg',
    appId: '1:745750974335:ios:33ad3adc507e9cc9a1144a',
    messagingSenderId: '745750974335',
    projectId: 'proyecto-eventos-1da9f',
    storageBucket: 'proyecto-eventos-1da9f.firebasestorage.app',
    iosBundleId: 'com.example.proyectoEventos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUbyYXWmxutsuexilGguNRkuOw3HnTt94',
    appId: '1:745750974335:web:49d25dde428426f5a1144a',
    messagingSenderId: '745750974335',
    projectId: 'proyecto-eventos-1da9f',
    authDomain: 'proyecto-eventos-1da9f.firebaseapp.com',
    storageBucket: 'proyecto-eventos-1da9f.firebasestorage.app',
    measurementId: 'G-KT67D500Q8',
  );
}
